<a href="https://colab.research.google.com/github/CholoRiego/Linear-Algebra-58019/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

from numpy.linalg import eig
A = np.array([[-12,3],[4,1]])
print(A,"\n")

B = np.array([[0],[0]])
print(B,"\n")

invA = np.linalg.inv(A)

X = np.dot(invA,B)
print(X,"\n")

#X = solve(A,B)
#print(X)

[[-12   3]
 [  4   1]] 

[[0]
 [0]] 

[[0.]
 [0.]] 



-----------------------------------

###EXAMPLE 1

In [32]:
C = np.array([[-6,3],[4,5]])
print(C)

w,v = np.linalg.eig(C)
print("\nThe eigenvalues is/are \n", w)
print("\nThe eigenvectors is are \n", v)

#x = v.round()
#print(x)

[[-6  3]
 [ 4  5]]

The eigenvalues is/are 
 [-7.  6.]

The eigenvectors is are 
 [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


###EXAMPLE 2

In [31]:
A = np.array([[2,2,4],[1,3,5],[2,3,4]])
print(A)

s,t = np.linalg.eig(A)
print("\nThe eigenvalues is/are \n", s.round())
print("\nThe eigenvectors is are \n", t.round())


D = np.dot(A,t.round())
print("\n",D)

[[2 2 4]
 [1 3 5]
 [2 3 4]]

The eigenvalues is/are 
 [ 9.  1. -1.]

The eigenvectors is are 
 [[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]

 [[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]


In [30]:
f = np.array([[-1],[-1],[-1]])
print(f)

g = np.dot(A,f)
print("\n",g)

[[-1]
 [-1]
 [-1]]

 [[-8]
 [-9]
 [-9]]
