<a href="https://colab.research.google.com/github/CholoRiego/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**FINAL EXAM**

##*Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)*

In [41]:
A = np.array([[1,1,1],[1,0,4],[0,0,5]])
B = np.array([[89],[89],[95]])
money = np.linalg.inv(A).dot(B)

print(money)

[[13.]
 [57.]
 [19.]]


##*Problem 2. Solve each system:*
###*3x - y + z = 5*
###*9x - 3y +3z = 15*
###*-12x +4y -4z = -20*

In [63]:
import numpy as np
X = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
Y = np.array([[5],[15],[-20]])

print(X,"\n")
print(Y,"\n")
#Z = np.linalg.inv(X).dot(Y)
determinant = np.linalg.det(X)
print("The determinant is: ", determinant)
print("The problem can not be solved due to it being a singular matrix or a matrix wherin the determinant is zero")

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]] 

[[  5]
 [ 15]
 [-20]] 

The determinant is:  0.0
The problem can not be solved due to it being a singular matrix or a matrix wherin the determinant is zero


##*Problem 3. Consider the matrix,*
###*Find the eigenvalue/s*
###*Find the eigenvectors*

In [53]:
E = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
x,y = np.linalg.eig(E)

print("\nThe eigenvalues is/are \n", x)
print("\nThe eigenvectors is are \n", y)



The eigenvalues is/are 
 [-1.  3.  2.]

The eigenvectors is are 
 [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
