<a href="https://colab.research.google.com/github/CholoRiego/Linear-Algebra-58019/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Using Python Codes, to find the inverse of a matrix 

##Inverse of A

In [4]:
import numpy as np
A = np.array([[4,3],[-5,9]])
invA = np.linalg.inv(A)
print(invA)

[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


##Array of Constants (B)

In [5]:
B = np.array([[20],[26]])
print(B)

[[20]
 [26]]


##Dot product of inverse of A and array of constants B

###Usage of linalg method

In [6]:
X = np.linalg.inv(A).dot(B)
print(X)


[[2.]
 [4.]]


###Without linalg method

In [8]:
x = np.dot(invA,B)
print(x)

[[2.]
 [4.]]


#You Can Try! (Trial Exercise)

In [11]:
a = np.array([[4,3,2],[-2,2,3],[3,-5,2]])
b = np.array([[25],[-10],[-4]])
X2 = np.linalg.inv(a).dot(b)
print(X2)

[[ 5.]
 [ 3.]
 [-2.]]
