<a href="https://colab.research.google.com/github/CholoRiego/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python Program to Inverse

In [12]:
import numpy as np
A = np.array([[1,2],[4,7]])
invA = np.linalg.inv(A)
print(invA)


[[-7.  2.]
 [ 4. -1.]]


In [14]:
C=np.dot(A,invA)
print(C)

[[1. 0.]
 [0. 1.]]


##Python Program to Transpose with 3x3 Matrix

In [18]:
a = np.array([[6,1,1],[4,-2,5],[2,8,7]])
b = np.transpose(a)
print(a, "\n\n")
print(b)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]] 


[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [21]:
C  = np.array([[6,1,1],[4,-2,5],[2,8,7]])
c = np.linalg.inv(C)
dotprodCc = np.dot(C,c)
print(dotprodCc)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]


#CODING  ACTIVITY #3

In [23]:
A = ( [[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]] )
print(A)

[[6, 1, 1, 3], [4, -2, 5, 1], [2, 8, 7, 6], [3, 1, 9, 7]]


###Inverse of A

In [24]:
invA = np.linalg.inv(A)
print(invA)

[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]


###Transpose of A


In [25]:
TranspA = np.transpose(A)
print(TranspA)

[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]


###Inverse-Transpose of A

In [26]:
invtranspA = np.transpose(invA)
print(invtranspA)

[[ 0.13368984 -0.00229183 -0.12987013  0.11000764]
 [ 0.10695187  0.02673797  0.18181818 -0.28342246]
 [ 0.02139037  0.14820474  0.06493506 -0.11382735]
 [-0.09090909 -0.12987013 -0.02597403  0.23376623]]
