<a href="https://colab.research.google.com/github/CholoRiego/Linear-Algebra-58019/blob/main/Matrix_and_Its_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Activity 1 - Matrix and Its Operations**

In [14]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
sum = A+B
print(sum)    #Summation of Matrices A and B

print(" ") #Line Break

difference1 = B-A
print(difference1)   #Difference of B to A

print(" ")  #Line Break

difference2 = A-B
print(difference2)   #Difference of A to B

[[ 1 -3]
 [ 6  4]]
 
[[11 -3]
 [-2  2]]
 
[[-11   3]
 [  2  -2]]
