<a href="https://colab.research.google.com/github/CholoRiego/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Midterm Exam

##Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [9]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


##Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [29]:
import numpy as np
B = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b = np.triu(B)
print(B, "\n\nWhen the elements below the principal diagonal is zero:\n")
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

When the elements below the principal diagonal is zero:

[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]


##Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [30]:
D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(D,'\n\n',"The symmetrical matrix is:\n")
d = np.transpose(D)
print(d)


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 The symmetrical matrix is:

[[1 4 7]
 [2 5 8]
 [3 6 9]]


##Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [21]:
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
invC = np.linalg.inv(C)
print(C, '\n')
print(invC)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]] 

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [32]:
print(C)
print("\nThe determinant of Matrix C is:\n", round(np.linalg.det(C)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

The determinant of Matrix C is:
 5


##Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [35]:
e = np.array([[5,4,1],[10,9,4],[10,13,15]])
f = np.array([[3.4],[8.8],[19.2]])
roots = np.linalg.inv(e).dot(f)
print(e,"\n\n",f,"\n\nThe roots are:")
print(roots)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]] 

 [[ 3.4]
 [ 8.8]
 [19.2]] 

The roots are:
[[0.2]
 [0.4]
 [0.8]]
