<a href="https://colab.research.google.com/github/CholoRiego/Linear-Algebra-58019/blob/main/Practial_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Practical Lab Exam 1**

##Problem 1

In [15]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])
print("A \n",A,"\n")
print("B \n",B,"\n")
print("C \n",C,"\n")
print("D \n",D,"\n")

A 
 [[1 2 3]
 [4 5 6]] 

B 
 [[1 2]
 [3 4]
 [5 6]] 

C 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

D 
 [[1 2]
 [3 4]] 



###a.AB

In [46]:
dot_prod = np.dot(A,B)
print(dot_prod)

[[22 28]
 [49 64]]


###b.D + D

In [24]:
sum = np.add(D,D)
print(sum)

[[2 4]
 [6 8]]


###c.2C

In [21]:
Times2 = 2*C
print(Times2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


#**Problem 2**

##Given the linear combination below, try to create a corresponding matrix representing it and display its type, shape, and its dimension.

Θ = 5x + 3y - z

###Matrix

In [29]:
import numpy as np
xyz = np.array([[5],[3],[1]])

print(xyz)

[[5]
 [3]
 [1]]


###Shape

In [35]:
xyz.shape

(3, 1)

###Dimension

In [31]:
xyz.ndim

2

###Type

In [44]:
print(type(xyz))


<class 'numpy.ndarray'>
