<a href="https://colab.research.google.com/github/CholoRiego/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PRELIM EXAM

##Question 1.Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C".

In [13]:
import numpy as np
C = np.eye(4)
print("Matrix C\n\n", C)

Matrix C

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##Question 2.In relation to Question 1, show a solution that doubles all the values of each element.

In [14]:
import numpy as np
DoubleC = 2*C
print("Double value of matrix C\n\n", DoubleC)

Double value of matrix C

 [[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


##Question 3. Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8].

In [5]:
import numpy as np
A = np.array([2,7,4])
B = np.array([3,9,8])

CrossProd = np.cross(A,B)

print("Cross Product of Matrix A and Matrix B\n\n", CrossProd)

Cross Product of Matrix A and Matrix B

 [20 -4 -3]
