<a href="https://colab.research.google.com/github/CholoRiego/Linear-Algebra-58019/blob/main/Python_Exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Python Exercise 2**

##Representing Vectors

In [6]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print("Vector A: " , A)
print("Vector B: " , B)

Vector A:  [4 3]
Vector B:  [ 2 -5]


##Describing Vectors on Numpy

In [13]:
import numpy as np

Ball1 = np.array([1,2,3])
Ball2 = np.array([-1,0,1])
pool = np.array([Ball1,Ball2])
pool.shape #(rows,columns)
pool.ndim #Dimension

2

In [17]:
w = np.array([[4,5,6],[7,8,9]])
w.size #Number of components inside matrix

6

##Addition of Vectors

###Simple addition

In [21]:
add1 = np.array([0,0,2])
add2 = np.array([1,2,3])
sum = add1+add2
sum


array([1, 2, 5])

###Usage of np.add

In [24]:
add1 = np.array([0,0,2])
add2 = np.array([1,2,3])
result = np.add(add1,add2)
result

array([1, 2, 5])

##Subtrating Vectors

###Simple Difference

In [25]:
diff = add1-add2
diff

array([-1, -2, -1])

###Usage of np.subtract

In [27]:
difference = np.subtract(add1,add2)
difference

array([-1, -2, -1])

##Scaling

In [28]:
A = np.array([1,3,5,7,9])
s = 5*A
s

array([ 5, 15, 25, 35, 45])

##Cross Product

In [34]:
a = np.array([2,3,4])
b = np.array([1,7,1])

output = np.cross(a,b) #(2x7)-(1x3) "\-/""
output

array([-25,   2,  11])

##Dot Product

In [36]:
c = np.array([2,3])
d = np.array([1,7])

outcome = np.dot(c,d)
outcome

23