<a href="https://colab.research.google.com/github/CholoRiego/Linear-Algebra-58019/blob/main/Vectors_Riego_de_Dios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **MATRIX ALGEBRA**

In [2]:
#numpy
import numpy as np
a = np.array([1,2,3])   #One by three matrix
print(a)

[1 2 3]


In [4]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])    #two by three matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
c = np.array([[1,2,3],[4,5,6],[7,8,9]])    #3x3 matrix
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
import numpy as np
d = np.full((3,3),7)
print(d)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [7]:
import numpy as np
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])   #diagonal matrix
print(e)

[1 5 9]


In [8]:
import numpy as np
f = np.eye(9)    #identity matrix
print(f)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [12]:
import numpy as np
g = np.zeros((5,6))    #Zero matrix
print(g)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
import numpy as np
h = np.empty((0,6))
print(h)

[]


In [20]:
import numpy as np
i = np.full((4,4), 2)
print(i)

j = np.full((4,4),3)
print(j)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
